# markdownlint config

# MD013/line-length: disable line length for all. We prefer lines as
# long as paragraph with in-editor line breaks.
MD013: false

# MD033/no-inline-html: allow often needed tags
MD033:
  allowed_elements:
    - br
    - dd
    - details
    - dl
    - dt
    - figcaption
    - figure
    - span
    - summary
    - lookbook-embed

# MD046/code-block-style: code block style conflicting with
# admonitions...
MD046: false

# MD048/code-fence-style: code fence style
MD048:
  style: backtick
