linters:
  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 4 # This is not good, but at least we don't want to be worse.
  EmbeddedEngines:
    enabled: true
    forbidden_engines:
      - coffee
      - css
      - sass
      - scss
      # - javascript TODO: Take care of this!
      - less
    exclude:
      - app/views/items/lti_exercise/tool_launch.html.slim # Known 'css' engine violation
  InstanceVariables:
    enabled: false # TODO: Take care of this!
    include:
      - app/views/**/_*.html.slim
  LineLength:
    enabled: false
