#

common: &common
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL", nil) %>
  pool_timeout: 5
  network_timeout: 5

development:
  <<: *common
  db: 3801

test:
  <<: *common
  db: 3802

integration:
  <<: *common
  db: 3803

production:
  <<: *common
  db: 3801
