# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5739a1f57c7b089007208825c9910c2a3782ba1c03987431ac14c7f3a5ca7c09f2da51cf17f4422beaf62eb6e76c8c1e949f3014d3069c2020d9e7df28183cab

test:
  secret_key_base: e05950593692c4a059a6ce3797eb6a8f5622309925a7a79ed74dfd4cd8c9a77afe6c974429073e46e36bef8b99d056c97da53be44eae1f6b32ffaa67238dcefa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
