---
services:
  minio:
    image: minio/minio@sha256:ed9be66eb5f2636c18289c34c3b725ddf57815f2777c77b5938543b78a44f144
    command: server /data
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: s3accesskey
      MINIO_SECRET_KEY: s3secretkey
    networks:
      - xikolo

  postgres:
    image: postgres:16.0-bookworm@sha256:a80d0c1b119cf3d6bab27f72782f16e47ab8534ced937fa813ec2ab26e1fd81e
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: xikolo
      PGUSER: xikolo
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --locale=C.UTF-8 --encoding=UTF8
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xikolo

  # RabbitMQ and Redis are explicitly started without persistent storage.
  # Restarting the stack purges all still pending background jobs or queued
  # messages.
  rabbitmq:
    image: rabbitmq:3.13-management@sha256:202e538f6eca805e9df875462f4b79d9e16e7e7e21ae9837336b655acb0a417f
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 8s
      retries: 12
    networks:
      - xikolo

  redis-cache:
    image: redis:7@sha256:ca65ea36ae16e709b0f1c7534bc7e5b5ac2e5bb3c97236e4fec00e3625eb678d
    command: redis-server --databases 8196
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - xikolo

  redis-sidekiq:
    image: redis:7@sha256:ca65ea36ae16e709b0f1c7534bc7e5b5ac2e5bb3c97236e4fec00e3625eb678d
    command: redis-server --databases 8196
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - xikolo

volumes:
  postgres:
  minio:

networks:
  xikolo:
    name: xikolo
