#

common: &common
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL", nil) %>
  pool_timeout: 5
  network_timeout: 5

development:
  <<: *common
  db: 3201

test:
  <<: *common
  db: 3202

integration:
  <<: *common
  db: 3203

production:
  <<: *common
  db: 3201
