common: &common
  uri: <%= ENV['XIKOLO_RABBITMQ_URL'] || 'amqp://localhost/' %>

test:
  <<: *common
  prefix: account-test
  pool_class: Msgr::TestPool

development:
  <<: *common

production:
  <<: *common

integration:
  <<: *common
