production:
  # Delete voucher claimant IPs at 4:15 a.m.
  delete_voucher_claimant_ip:
    cron: "15 4 * * *"
    class: Voucher::DeleteClaimantIPJob
    queue: default
    active_job: true
  # Synchronize newly added videos every 2 hours.
  sync_videos:
    cron: "0 */2 * * *"
    class: Video::SyncVideosJob
    queue: long_running
    active_job: true
