common: &common
  uri: <%= ENV['XIKOLO_RABBITMQ_URL'] || 'amqp://localhost/' %>
  checkcredentials: false

assets:
  <<: *common

integration:
  <<: *common

test:
  <<: *common
  prefix: web-test
  pool_class: Msgr::TestPool
  raise_exceptions: true

development:
  <<: *common

production:
  <<: *common
