#

common: &common
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL", nil) %>
  pool_timeout: 5
  network_timeout: 5

development:
  <<: *common
  db: 3001

test:
  <<: *common
  db: 3002

integration:
  <<: *common
  db: 3003

production:
  <<: *common
  db: 3001
