#

common: &common
  url: <%= ENV.fetch("SIDEKIQ_REDIS_URL", nil) %>
  pool_timeout: 5
  network_timeout: 5

development:
  <<: *common
  db: 6301

test:
  <<: *common
  db: 6302

integration:
  <<: *common
  db: 6303

production:
  <<: *common
  db: 6301
