---
s3:
  buckets:
    collabspace: bucket-collabspace
    uploads: bucket-uploads

  # connect_info:
  #   endpoint: https://s3.openhpicloud.de
  #   region: default
  #   access_key_id: ...
  #   secret_access_key: ...
